### ISSUE TITLE
Project not running/starting after install

### ISSUE THREAD

**Issue by hudsonkb** [metral/scores#1]
Hello.  first thanks in advance for your work on this project.  I'm attempting to get this running using the latest raspian release.  I performed the installation from the readme and install.sh.  It appears there are a few warnings/errors that come up during install.  Can you take a look and help me with resolution?  You can contact me via email at hudson_kb@hotmail.com.  thank you.

Here's is the install log:

pi@raspberrypi ~ $ git clone https://github.com/metral/scores.git
Cloning into 'scores'...
remote: Counting objects: 15, done.
remote: Total 15 (delta 0), reused 0 (delta 0), pack-reused 15
Unpacking objects: 100% (15/15), done.
pi@raspberrypi ~ $ cd scores/
pi@raspberrypi ~/scores $ git submodule init ; git submodule update
Submodule 'led_sign' (https://github.com/metral/led_sign.git) registered for path 'led_sign'
Cloning into 'led_sign'...
remote: Counting objects: 104, done.
remote: Total 104 (delta 0), reused 0 (delta 0), pack-reused 104
Receiving objects: 100% (104/104), 14.71 KiB, done.
Resolving deltas: 100% (59/59), done.
Submodule path 'led_sign': checked out '145f7df1762bd88537aff936913b9d9766a8d699'
pi@raspberrypi ~/scores $ cd..
bash: cd..: command not found
pi@raspberrypi ~/scores $ cd
pi@raspberrypi ~ $ ./install.sh
bash: ./install.sh: No such file or directory
pi@raspberrypi ~ $ cd scores/
pi@raspberrypi ~/scores $ ./install.sh
Hit http://raspberrypi.collabora.com wheezy Release.gpg
Get:1 http://archive.raspberrypi.org wheezy Release.gpg [490 B]  
Hit http://raspberrypi.collabora.com wheezy Release  
Get:2 http://mirrordirector.raspbian.org wheezy Release.gpg [490 B]
Get:3 http://archive.raspberrypi.org wheezy Release [15.4 kB]
Get:4 http://mirrordirector.raspbian.org wheezy Release [14.4 kB]  
Hit http://raspberrypi.collabora.com wheezy/rpi armhf Packages  
Get:5 http://archive.raspberrypi.org wheezy/main armhf Packages [129 kB]
Get:6 http://mirrordirector.raspbian.org wheezy/main armhf Packages [6,903 kB] 
Ign http://raspberrypi.collabora.com wheezy/rpi Translation-en_GB  
Ign http://raspberrypi.collabora.com wheezy/rpi Translation-en  
Ign http://archive.raspberrypi.org wheezy/main Translation-en_GB
Ign http://archive.raspberrypi.org wheezy/main Translation-en
Get:7 http://mirrordirector.raspbian.org wheezy/contrib armhf Packages [23.6 kB]
Get:8 http://mirrordirector.raspbian.org wheezy/non-free armhf Packages [49.3 kB]
Get:9 http://mirrordirector.raspbian.org wheezy/rpi armhf Packages [592 B]  
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en_GB  
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en  
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en_GB  
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en  
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en_GB  
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en  
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en_GB  
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en  
Fetched 7,136 kB in 44s (160 kB/s)  
Reading package lists... Done
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following NEW packages will be installed:
  pwgen
0 upgraded, 1 newly installed, 0 to remove and 11 not upgraded.
Need to get 20.1 kB of archives.
After this operation, 67.6 kB of additional disk space will be used.
Get:1 http://mirrordirector.raspbian.org/raspbian/ wheezy/main pwgen armhf 2.06-1 [20.1 kB]
Fetched 20.1 kB in 0s (23.0 kB/s)
Selecting previously unselected package pwgen.
(Reading database ... 77851 files and directories currently installed.)
Unpacking pwgen (from .../pwgen_2.06-1_armhf.deb) ...
Processing triggers for man-db ...
Setting up pwgen (2.06-1) ...
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following extra packages will be installed:
  libexpat1-dev libssl-dev libssl-doc libssl1.0.0 python2.7-dev
The following NEW packages will be installed:
  libexpat1-dev libssl-dev libssl-doc python-dev python2.7-dev
The following packages will be upgraded:
  libssl1.0.0
1 upgraded, 5 newly installed, 0 to remove and 10 not upgraded.
Need to get 32.7 MB of archives.
After this operation, 42.0 MB of additional disk space will be used.
Get:1 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libssl1.0.0 armhf 1.0.1e-2+rvt+deb7u17 [1,053 kB]
Get:2 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libexpat1-dev armhf 2.1.0-1+deb7u1 [210 kB]
Get:3 http://mirrordirector.raspbian.org/raspbian/ wheezy/main python-dev all 2.7.3-4+deb7u1 [920 B]
Get:4 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libssl-dev armhf 1.0.1e-2+rvt+deb7u17 [1,500 kB]
Get:5 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libssl-doc all 1.0.1e-2+rvt+deb7u17 [1,199 kB]
Get:6 http://mirrordirector.raspbian.org/raspbian/ wheezy/main python2.7-dev armhf 2.7.3-6+deb7u2 [28.7 MB]
Fetched 32.7 MB in 23s (1,385 kB/s)  
Preconfiguring packages ...
(Reading database ... 77857 files and directories currently installed.)
Preparing to replace libssl1.0.0:armhf 1.0.1e-2+rvt+deb7u16 (using .../libssl1.0.0_1.0.1e-2+rvt+deb7u17_armhf.deb) ...
Unpacking replacement libssl1.0.0:armhf ...
Selecting previously unselected package libexpat1-dev.
Unpacking libexpat1-dev (from .../libexpat1-dev_2.1.0-1+deb7u1_armhf.deb) ...
Selecting previously unselected package libssl-dev.
Unpacking libssl-dev (from .../libssl-dev_1.0.1e-2+rvt+deb7u17_armhf.deb) ...
Selecting previously unselected package libssl-doc.
Unpacking libssl-doc (from .../libssl-doc_1.0.1e-2+rvt+deb7u17_all.deb) ...
Selecting previously unselected package python2.7-dev.
Unpacking python2.7-dev (from .../python2.7-dev_2.7.3-6+deb7u2_armhf.deb) ...
Selecting previously unselected package python-dev.
Unpacking python-dev (from .../python-dev_2.7.3-4+deb7u1_all.deb) ...
Processing triggers for man-db ...
Setting up libssl1.0.0:armhf (1.0.1e-2+rvt+deb7u17) ...
Setting up libexpat1-dev (2.1.0-1+deb7u1) ...
Setting up libssl-dev (1.0.1e-2+rvt+deb7u17) ...
Setting up libssl-doc (1.0.1e-2+rvt+deb7u17) ...
Setting up python2.7-dev (2.7.3-6+deb7u2) ...
Setting up python-dev (2.7.3-4+deb7u1) ...
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following extra packages will be installed:
  heirloom-mailx libaio1 libdbd-mysql-perl libdbi-perl libhtml-template-perl
  libmysqlclient16 mysql-client-5.5 mysql-common mysql-server-5.5
  mysql-server-core-5.5
Suggested packages:
  exim4 mail-transport-agent libipc-sharedcache-perl libterm-readkey-perl
  tinyca
Recommended packages:
  mailx
The following NEW packages will be installed:
  heirloom-mailx libaio1 libdbd-mysql-perl libdbi-perl libhtml-template-perl
  libmysqlclient16 mysql-client-5.5 mysql-common mysql-server mysql-server-5.5
  mysql-server-core-5.5
0 upgraded, 11 newly installed, 0 to remove and 10 not upgraded.
Need to get 9,775 kB of archives.
After this operation, 90.7 MB of additional disk space will be used.
Get:1 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libaio1 armhf 0.3.109-3 [8,944 B]
Get:2 http://mirrordirector.raspbian.org/raspbian/ wheezy/main mysql-common all 5.5.43-0+deb7u1 [73.4 kB]
Get:3 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libdbi-perl armhf 1.622-1+deb7u1 [890 kB]
Get:4 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libmysqlclient16 armhf 5.1.62-1 [1,828 kB]
Get:5 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libdbd-mysql-perl armhf 4.021-1 [123 kB]
Get:6 http://mirrordirector.raspbian.org/raspbian/ wheezy/main mysql-client-5.5 armhf 5.5.43-0+deb7u1 [1,450 kB]
Get:7 http://mirrordirector.raspbian.org/raspbian/ wheezy/main mysql-server-core-5.5 armhf 5.5.43-0+deb7u1 [3,396 kB]
Get:8 http://mirrordirector.raspbian.org/raspbian/ wheezy/main mysql-server-5.5 armhf 5.5.43-0+deb7u1 [1,609 kB]
Get:9 http://mirrordirector.raspbian.org/raspbian/ wheezy/main heirloom-mailx armhf 12.5-2+deb7u1 [254 kB]
Get:10 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libhtml-template-perl all 2.91-1 [72.0 kB]
Get:11 http://mirrordirector.raspbian.org/raspbian/ wheezy/main mysql-server all 5.5.43-0+deb7u1 [71.7 kB]
Fetched 9,775 kB in 9s (1,069 kB/s)  
Preconfiguring packages ...
Selecting previously unselected package libaio1:armhf.
(Reading database ... 79409 files and directories currently installed.)
Unpacking libaio1:armhf (from .../libaio1_0.3.109-3_armhf.deb) ...
Selecting previously unselected package mysql-common.
Unpacking mysql-common (from .../mysql-common_5.5.43-0+deb7u1_all.deb) ...
Selecting previously unselected package libdbi-perl.
Unpacking libdbi-perl (from .../libdbi-perl_1.622-1+deb7u1_armhf.deb) ...
Selecting previously unselected package libmysqlclient16.
Unpacking libmysqlclient16 (from .../libmysqlclient16_5.1.62-1_armhf.deb) ...
Selecting previously unselected package libdbd-mysql-perl.
Unpacking libdbd-mysql-perl (from .../libdbd-mysql-perl_4.021-1_armhf.deb) ...
Selecting previously unselected package mysql-client-5.5.
Unpacking mysql-client-5.5 (from .../mysql-client-5.5_5.5.43-0+deb7u1_armhf.deb) ...
Selecting previously unselected package mysql-server-core-5.5.
Unpacking mysql-server-core-5.5 (from .../mysql-server-core-5.5_5.5.43-0+deb7u1_armhf.deb) ...
Processing triggers for man-db ...
Setting up mysql-common (5.5.43-0+deb7u1) ...
Selecting previously unselected package mysql-server-5.5.
(Reading database ... 79758 files and directories currently installed.)
Unpacking mysql-server-5.5 (from .../mysql-server-5.5_5.5.43-0+deb7u1_armhf.deb) ...
Selecting previously unselected package heirloom-mailx.
Unpacking heirloom-mailx (from .../heirloom-mailx_12.5-2+deb7u1_armhf.deb) ...
Selecting previously unselected package libhtml-template-perl.
Unpacking libhtml-template-perl (from .../libhtml-template-perl_2.91-1_all.deb) ...
Selecting previously unselected package mysql-server.
Unpacking mysql-server (from .../mysql-server_5.5.43-0+deb7u1_all.deb) ...
Processing triggers for man-db ...
Processing triggers for menu ...
Setting up libaio1:armhf (0.3.109-3) ...
Setting up libdbi-perl (1.622-1+deb7u1) ...
Setting up libmysqlclient16 (5.1.62-1) ...
Setting up libdbd-mysql-perl (4.021-1) ...
Setting up mysql-client-5.5 (5.5.43-0+deb7u1) ...
Setting up mysql-server-core-5.5 (5.5.43-0+deb7u1) ...
Setting up mysql-server-5.5 (5.5.43-0+deb7u1) ...
[ ok ] Stopping MySQL database server: mysqld.
150623 20:01:33 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
150623 20:01:33 [Note] /usr/sbin/mysqld (mysqld 5.5.43-0+deb7u1) starting as process 10909 ...
150623 20:01:33 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
150623 20:01:33 [Note] Plugin 'FEDERATED' is disabled.
150623 20:01:33 InnoDB: The InnoDB memory heap is disabled
150623 20:01:33 InnoDB: Mutexes and rw_locks use GCC atomic builtins
150623 20:01:33 InnoDB: Compressed tables use zlib 1.2.7
150623 20:01:33 InnoDB: Using Linux native AIO
150623 20:01:33 InnoDB: Initializing buffer pool, size = 128.0M
150623 20:01:34 InnoDB: Completed initialization of buffer pool
150623 20:01:34 InnoDB: highest supported file format is Barracuda.
150623 20:01:35  InnoDB: Waiting for the background threads to start
150623 20:01:36 InnoDB: 5.5.43 started; log sequence number 1595675
150623 20:01:37  InnoDB: Starting shutdown...
150623 20:01:38  InnoDB: Shutdown completed; log sequence number 1595675
[ ok ] Starting MySQL database server: mysqld . . . ..
[info] Checking for tables which need an upgrade, are corrupt or were 
not closed cleanly..
Setting up heirloom-mailx (12.5-2+deb7u1) ...
update-alternatives: using /usr/bin/heirloom-mailx to provide /usr/bin/mailx (mailx) in auto mode
Setting up libhtml-template-perl (2.91-1) ...
Setting up mysql-server (5.5.43-0+deb7u1) ...
Processing triggers for menu ...
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following extra packages will be installed:
  libmysqlclient18 python-pkg-resources
Suggested packages:
  python-egenix-mxdatetime python-mysqldb-dbg python-distribute
  python-distribute-doc
The following NEW packages will be installed:
  libmysqlclient18 python-mysqldb python-pkg-resources python-setuptools
0 upgraded, 4 newly installed, 0 to remove and 10 not upgraded.
Need to get 1,216 kB of archives.
After this operation, 4,838 kB of additional disk space will be used.
Get:1 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libmysqlclient18 armhf 5.5.43-0+deb7u1 [618 kB]
Get:2 http://mirrordirector.raspbian.org/raspbian/ wheezy/main python-mysqldb armhf 1.2.3-2 [84.9 kB]
Get:3 http://mirrordirector.raspbian.org/raspbian/ wheezy/main python-pkg-resources all 0.6.24-1 [63.6 kB]
Get:4 http://mirrordirector.raspbian.org/raspbian/ wheezy/main python-setuptools all 0.6.24-1 [449 kB]
Fetched 1,216 kB in 2s (577 kB/s)  
Selecting previously unselected package libmysqlclient18:armhf.
(Reading database ... 79869 files and directories currently installed.)
Unpacking libmysqlclient18:armhf (from .../libmysqlclient18_5.5.43-0+deb7u1_armhf.deb) ...
Selecting previously unselected package python-mysqldb.
Unpacking python-mysqldb (from .../python-mysqldb_1.2.3-2_armhf.deb) ...
Selecting previously unselected package python-pkg-resources.
Unpacking python-pkg-resources (from .../python-pkg-resources_0.6.24-1_all.deb) ...
Selecting previously unselected package python-setuptools.
Unpacking python-setuptools (from .../python-setuptools_0.6.24-1_all.deb) ...
Setting up libmysqlclient18:armhf (5.5.43-0+deb7u1) ...
Setting up python-mysqldb (1.2.3-2) ...
Setting up python-pkg-resources (0.6.24-1) ...
Setting up python-setuptools (0.6.24-1) ...
Reading package lists... Done
Building dependency tree  
Reading state information... Done
curl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   314    0   314    0     0    515      0 --:--:-- --:--:-- --:--:--  1071
100  296k  100  296k    0     0   257k      0  0:00:01  0:00:01 --:--:-- 1037k
!
! Can't write to /usr/local/share/perl/5.14.2 and /usr/local/bin: Installing modules to /home/pi/perl5
! To turn off this warning, you have to do one of the following:
!   - run me as a root or with --sudo option (to install to /usr/local/share/perl/5.14.2 and /usr/local/bin)
!   - Configure local::lib your existing local::lib in this shell to set PERL_MM_OPT etc.
!   - Install local::lib by running the following commands
!
!         cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
!
--> Working on App::cpanminus
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7038.tar.gz ... OK
==> Found dependencies: ExtUtils::MakeMaker
--> Working on ExtUtils::MakeMaker
Fetching http://www.cpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.04.tar.gz ... OK
Configuring ExtUtils-MakeMaker-7.04 ... OK
Building ExtUtils-MakeMaker-7.04 ... OK
Successfully installed ExtUtils-MakeMaker-7.04 (upgraded from 6.57_05)
Configuring App-cpanminus-1.7038 ... OK
Building and testing App-cpanminus-1.7038 ... OK
Successfully installed App-cpanminus-1.7038
2 distributions installed
Searching for pip
Reading http://pypi.python.org/simple/pip/
Best match: pip 7.0.3
Downloading https://pypi.python.org/packages/source/p/pip/pip-7.0.3.tar.gz#md5=54cbf5ae000fb3af3367345f5d299d1c
Processing pip-7.0.3.tar.gz
Running pip-7.0.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-DvnvL8/pip-7.0.3/egg-dist-tmp-4orDtw
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'
Adding pip 7.0.3 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
Searching for pytz
Reading http://pypi.python.org/simple/pytz/
Best match: pytz 2015.4
Downloading https://pypi.python.org/packages/2.7/p/pytz/pytz-2015.4-py2.7.egg#md5=4698c08f18f5cecba09b7e85d8e9328e
Processing pytz-2015.4-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/pytz-2015.4-py2.7.egg
Extracting pytz-2015.4-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding pytz 2015.4 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pytz-2015.4-py2.7.egg
Processing dependencies for pytz
Finished processing dependencies for pytz
Searching for elementtree
Reading http://pypi.python.org/simple/elementtree/
Reading http://effbot.org/downloads#elementtree
Reading http://effbot.org/zone/element-index.htm
Best match: elementtree 1.2.7-20070827-preview
Downloading http://effbot.org/media/downloads/elementtree-1.2.7-20070827-preview.zip
Processing elementtree-1.2.7-20070827-preview.zip
Running elementtree-1.2.7-20070827-preview/setup.py -q bdist_egg --dist-dir /tmp/easy_install-7SKNX1/elementtree-1.2.7-20070827-preview/egg-dist-tmp-5kBsrL
zip_safe flag not set; analyzing archive contents...
Adding elementtree 1.2.7-20070827-preview to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/elementtree-1.2.7_20070827_preview-py2.7.egg
Processing dependencies for elementtree
Finished processing dependencies for elementtree
/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting SQLAlchemy
/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading SQLAlchemy-1.0.5.tar.gz (4.6MB)
    100% |████████████████████████████████| 4.6MB 2.5kB/s 
Installing collected packages: SQLAlchemy
  Running setup.py install for SQLAlchemy
Successfully installed SQLAlchemy-1.0.5
Collecting python-dateutil
/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading python_dateutil-2.4.2-py2.py3-none-any.whl (188kB)
    100% |████████████████████████████████| 192kB 52kB/s 
Collecting six>=1.5 (from python-dateutil)
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil
Successfully installed python-dateutil-2.4.2 six-1.9.0
sudo: cpanm: command not found
Collecting supervisor
/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading supervisor-3.1.3.tar.gz (391kB)
    100% |████████████████████████████████| 393kB 38kB/s 
Collecting meld3>=0.6.5 (from supervisor)
  Downloading meld3-1.0.2-py2.py3-none-any.whl
Installing collected packages: meld3, supervisor
  Running setup.py install for supervisor
Successfully installed meld3-1.0.2 supervisor-3.1.3
Traceback (most recent call last):
  File "/usr/local/bin/supervisorctl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5
supervisord: no process found
Traceback (most recent call last):
  File "/usr/local/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5

**Comment by metral** [comment]
hey there - thanks for the kind words. unfortuantetly, i no longer support this repo, and haven't for quite some time. howevert, looking through your logs it looks like you're having issues installing cpanm (what is used to install the modules to talk to the led) - try searching for how to install that as it seems the method used in the install script is broken. start here http://raspberrypi.stackexchange.com/questions/1901/compiling-for-cpan-not-possible-on-raspbian

hope this helps

**Comment by hudsonkb** [comment]
Thank you.  I manged to get MiniLED device installed.  Now i'm dealing with the supervisord issue down near the end of the log.  I think i found something to try here for resolution:

https://github.com/Supervisor/meld3/issues/21

Just curious...do you know if this is still running for the friend you built it for?  I'm curious if the fetching of the scores method is still working, because that might be a deal breaker for me since it would likely require some re-coding in that particular area for changes in the data source.

edit: Looks like the source will still work via the test hit below:

view-source:http://scores.nbcsports.msnbc.com/ticker/data/gamesMSNBC.js.asp?jsonp=true&sport=MLB&period=20150624

with a little luck maybe i'll have it working this evening

**Comment by hudsonkb** [comment]
FYI I started it via main.py directly and can confirm it is working, feeding and displaying on the led as it should.   Supervisor control still not working, but I understand the concept and will continue to try to get that fixed up in the next day or two.  Thanks again...this is really cool.  Not really a big Linux or Python person, so the learning was fun.

**Comment by metral** [comment]
You're welcome - glad to hear you powered through the issues and that its
working :)

On Thu, Jun 25, 2015 at 5:55 AM, hudsonkb notifications@github.com wrote:

> FYI I started it via main.py directly and can confirm it is working,
> feeding and displaying on the led as it should. Supervisor control still
> not working, but I understand the concept and will continue to try to get
> that fixed up in the next day or two. Thanks again...this is really cool.
> Not really a big Linux or Python person, so the learning was fun.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/metral/scores/issues/1#issuecomment-115243422.

## 

-Mike Metral

**Comment by jfergs21** [comment]
Hey @hudsonkb -- I would love to hear if you have any progress on this. I cannot seem to even get the display to LED working, but also having the supervisord issue. If you have some time it would be awesome to hear some of your troubleshooting methods. Contact me @ jarrod (at) uvic.ca
